import { filterEarthEvents, type EarthEventType, type GeocodeResult } from '@earth-pulse/shared';
import { AlertTriangle, RefreshCw } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import { ActivityPanel } from '@/components/ActivityPanel';
import { EarthMap } from '@/components/EarthMap';
import { EventDetails } from '@/components/EventDetails';
import { EventFeed } from '@/components/EventFeed';
import { Header } from '@/components/Header';
import { Button } from '@/components/ui/button';
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle } from '@/components/ui/sheet';
import { TooltipProvider } from '@/components/ui/tooltip';
import { useEarthEvents } from '@/hooks/useEarthEvents';
import { useIsMobile } from '@/hooks/use-mobile';
import { useObservations } from '@/hooks/useObservations';
import { useNearby, type NearbyLocation } from '@/hooks/useNearby';
import { useSpaceWeather } from '@/hooks/useSpaceWeather';
import { useViewportEvents, type ViewportBounds } from '@/hooks/useViewportEvents';
const filters: { label: string; value: EarthEventType }[] = [{ label: 'Earthquakes', value: 'earthquake' }, { label: 'Wildfires', value: 'wildfire' }, { label: 'Storms', value: 'storm' }, { label: 'Weather alerts', value: 'weather-alert' }, { label: 'Volcanoes', value: 'volcano' }, { label: 'Floods', value: 'flood' }, { label: 'Other', value: 'other' }];
const allTypes = new Set<EarthEventType>(['earthquake', 'wildfire', 'storm', 'flood', 'volcano', 'drought', 'landslide', 'weather-alert', 'ice', 'dust', 'other']);
export function App() { const { data, error, isLoading, isRefreshing, refresh } = useEarthEvents(); const observations = useObservations(); const [activeTypes, setActiveTypes] = useState<Set<EarthEventType>>(new Set(allTypes)); const [feedLimit, setFeedLimit] = useState(50); const [selectedId, setSelectedId] = useState<string>(); const [placeTarget, setPlaceTarget] = useState<GeocodeResult>(); const [viewport, setViewport] = useState<ViewportBounds>(); const [nearbyLocation, setNearbyLocation] = useState<NearbyLocation>(); const [radiusKm, setRadiusKm] = useState(160.934); const [locationError, setLocationError] = useState<string>(); const [locating, setLocating] = useState(false); const nearby = useNearby(nearbyLocation, radiusKm); const spaceWeather = useSpaceWeather(); const viewportEvents = useViewportEvents(viewport); const isMobile = useIsMobile(); const events = useMemo(() => data?.events ?? [], [data?.events]); const mapEvents = viewportEvents.data?.events ?? events; const visibleEvents = useMemo(() => filterEarthEvents(events, activeTypes), [events, activeTypes]); const feedEvents = useMemo(() => visibleEvents.slice(0, feedLimit), [feedLimit, visibleEvents]); const visibleMapEvents = useMemo(() => filterEarthEvents(mapEvents, activeTypes), [mapEvents, activeTypes]); const selected = events.find((event) => event.id === selectedId) ?? mapEvents.find((event) => event.id === selectedId);
  useEffect(() => { setFeedLimit(50); }, [activeTypes]);
  useEffect(() => { if (selected && !activeTypes.has(selected.type)) setSelectedId(undefined); }, [activeTypes, selected]);
  const toggle = (type: EarthEventType) => setActiveTypes((current) => { const next = new Set(current); if (next.has(type)) next.delete(type); else next.add(type); return next.size ? next : new Set(allTypes); });
  function useMyLocation() { if (!navigator.geolocation) { setLocationError('Location is not available in this browser.'); return; } setLocating(true); setLocationError(undefined); navigator.geolocation.getCurrentPosition((position) => { setNearbyLocation({ latitude: position.coords.latitude, longitude: position.coords.longitude, label: position.coords.accuracy > 5_000 ? 'Approximate device location' : 'Device location' }); setPlaceTarget(undefined); setSelectedId(undefined); setLocating(false); }, (positionError) => { setLocating(false); setLocationError(positionError.code === positionError.PERMISSION_DENIED ? 'Location permission was not granted.' : 'Your location could not be determined.'); }, { enableHighAccuracy: false, timeout: 10_000, maximumAge: 300_000 }); }
  const selectedRelations = selected ? data?.relations.filter((relation) => relation.subjectEventId === selected.id || relation.relatedEventId === selected.id || relation.eventIds?.includes(selected.id)) : [];
  return <TooltipProvider><div className="app-shell"><Header fetchedAt={data?.meta.fetchedAt} providers={data?.meta.providers} live={data?.meta.cache === 'fresh' && !error} refreshing={isRefreshing} onRefresh={refresh} onPlaceSelect={(result) => { setPlaceTarget(result); setNearbyLocation({ latitude: result.latitude, longitude: result.longitude, label: result.label }); setSelectedId(undefined); }} />{(data?.meta.warning || (error && data)) && <div className="warning-banner" role="status"><AlertTriangle /><span>{data?.meta.warning?.message ?? error}</span></div>}<nav className="filter-bar" aria-label="Natural event filters"><span>DISPLAY FILTER</span><div><button type="button" className={activeTypes.size === allTypes.size ? 'active' : ''} aria-pressed={activeTypes.size === allTypes.size} onClick={() => setActiveTypes(new Set(allTypes))}>All<small>{events.length}</small></button>{filters.map((filter) => <button key={filter.value} type="button" className={activeTypes.has(filter.value) ? 'active' : ''} aria-pressed={activeTypes.has(filter.value)} onClick={() => toggle(filter.value)}>{filter.label}<small>{events.filter((event) => event.type === filter.value).length}</small></button>)}</div><p><span className="visible-dot" /> {visibleEvents.length} visible signals</p></nav>{error && !data ? <main className="hard-error"><div><AlertTriangle /><p className="eyebrow">DATA LINK INTERRUPTED</p><h1>Natural event feed unavailable</h1><p>{error}</p><Button onClick={refresh}><RefreshCw /> Retry connection</Button></div></main> : <main className="dashboard-grid"><EventFeed events={feedEvents} total={visibleEvents.length} selectedId={selectedId} onSelect={(event) => { setSelectedId(event.id); setPlaceTarget(undefined); }} onShowMore={() => setFeedLimit((limit) => limit + 50)} loading={isLoading} /><EarthMap events={visibleMapEvents} observations={observations?.features ?? []} selected={selected} placeTarget={placeTarget} nearbyLocation={nearbyLocation} radiusKm={radiusKm} onViewportChange={setViewport} onSelect={(event) => { setSelectedId(event.id); setPlaceTarget(undefined); }} /><ActivityPanel summary={data?.summary} selected={selected} relations={selectedRelations} nearby={nearby.data} nearbyLoading={nearby.isFetching} nearbyError={locationError ?? (nearby.error instanceof Error ? nearby.error.message : undefined)} radiusKm={radiusKm} onRadiusChange={setRadiusKm} onUseMyLocation={useMyLocation} locating={locating} spaceWeather={spaceWeather.data} /></main>}<Sheet open={Boolean(isMobile && selected)} onOpenChange={(open) => { if (!open) setSelectedId(undefined); }}><SheetContent side="bottom" className="mobile-sheet"><SheetHeader><SheetTitle>Selected activity</SheetTitle><SheetDescription>Earth Pulse event details</SheetDescription></SheetHeader>{selected && <EventDetails event={selected} relations={selectedRelations} />}</SheetContent></Sheet></div></TooltipProvider>; }
