import { render, screen, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { afterEach, describe, expect, it, vi } from 'vitest';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { App } from './App';
vi.mock('@/components/EarthMap', () => ({ EarthMap: () => <div aria-label="Interactive global natural events map" /> }));
const providers = { usgs: { configured: true, healthy: true, state: 'ok', lastSuccess: '2026-01-01T00:00:00.000Z', cacheAgeSeconds: 0 }, eonet: { configured: true, healthy: true, state: 'ok', lastSuccess: '2026-01-01T00:00:00.000Z', cacheAgeSeconds: 0 }, firms: { configured: false, healthy: false, state: 'unconfigured', lastSuccess: null, cacheAgeSeconds: null }, nws: { configured: true, healthy: true, state: 'ok', lastSuccess: '2026-01-01T00:00:00.000Z', cacheAgeSeconds: 0 } };
const response = { events: [{ id: 'quake-1', type: 'earthquake', title: 'M 4.6 - Test Ridge', latitude: 1, longitude: 2, startedAt: '2026-01-01T00:00:00.000Z', severity: 'high', severityScore: 46, source: 'USGS', metadata: { kind: 'earthquake', magnitude: 4.6, depthKm: 12, place: 'Test Ridge' } }, { id: 'eonet-1', type: 'volcano', title: 'Etna activity', latitude: 37, longitude: 15, startedAt: '2026-01-01T00:00:00.000Z', severity: 'high', severityScore: 60, source: 'NASA EONET', metadata: { kind: 'eonet', category: 'Volcanoes', open: true, sources: [], geometryHistory: [] } }], relations: [], summary: { activeEvents: 2, earthquakes: 1, naturalEvents: 1, significantWeatherAlerts: 0, wildfireDetectionCount: 0, strongestEarthquake: null, highestSeverityEvent: null, pulseScore: 22, pulseBand: 'normal', refreshedAt: '2026-01-01T00:00:00.000Z' }, meta: { fetchedAt: '2026-01-01T00:00:00.000Z', servedAt: '2026-01-01T00:00:00.000Z', cache: 'fresh', rejectedCount: 0, providers } };
describe('Earth Pulse dashboard', () => { afterEach(() => vi.restoreAllMocks()); it('loads multi-source events, filters them, and opens synchronized details', async () => { vi.stubGlobal('fetch', vi.fn(async (url: string) => url.includes('/api/observations') ? new Response('{}', { status: 503 }) : new Response(JSON.stringify(response), { status: 200 }))); const user = userEvent.setup(); render(<QueryClientProvider client={new QueryClient({ defaultOptions: { queries: { retry: false } } })}><App /></QueryClientProvider>); expect((await screen.findAllByText(/Test Ridge/)).length).toBeGreaterThan(0); await user.click(screen.getByText('Volcanoes')); expect(screen.queryByText(/Volcanoes — Volcanoes/)).not.toBeInTheDocument(); await user.click(screen.getByText('Earthquakes')); expect(screen.getByText('No events in this view')).toBeInTheDocument(); await user.click(screen.getByText('All')); await user.click((await screen.findAllByText(/Test Ridge/))[0]!); await waitFor(() => expect(screen.getByText('Selected activity')).toBeInTheDocument()); expect(screen.getByText(/not official risk assessments/)).toBeInTheDocument(); }); });
