import type { EarthEvent, GeocodeResult, ObservationFeature } from '@earth-pulse/shared';
import maplibregl, { type GeoJSONSource, type MapLayerMouseEvent } from 'maplibre-gl';
import { Crosshair, Minus, Plus } from 'lucide-react';
import { useEffect, useRef, useState } from 'react';
import type { NearbyLocation } from '@/hooks/useNearby';
import type { ViewportBounds } from '@/hooks/useViewportEvents';
import { Button } from '@/components/ui/button';
import { alertPolygons, emptyCollection, eventPoints, wildfireFeatures } from './map/layerData';

interface Props { events: EarthEvent[]; observations: ObservationFeature[]; selected: EarthEvent | undefined; selectedFire?: ObservationFeature | undefined; placeTarget: GeocodeResult | undefined; nearbyLocation?: NearbyLocation | undefined; radiusKm?: number | undefined; onSelect: (event: EarthEvent) => void; onSelectFire: (feature: ObservationFeature) => void; onViewportChange?: ((bounds: ViewportBounds) => void) | undefined; }

export function EarthMap({ events, observations, selected, selectedFire, placeTarget, nearbyLocation, radiusKm, onSelect, onSelectFire, onViewportChange }: Props) {
  const containerRef = useRef<HTMLDivElement>(null); const mapRef = useRef<maplibregl.Map | undefined>(undefined); const eventsRef = useRef(events); const observationsRef = useRef(observations); const onSelectRef = useRef(onSelect); const onSelectFireRef = useRef(onSelectFire); const onViewportChangeRef = useRef(onViewportChange); const [mapError, setMapError] = useState(false); eventsRef.current = events; observationsRef.current = observations; onSelectRef.current = onSelect; onSelectFireRef.current = onSelectFire; onViewportChangeRef.current = onViewportChange;
  useEffect(() => {
    if (!containerRef.current || mapRef.current) return;
    const map = new maplibregl.Map({ container: containerRef.current, style: import.meta.env.VITE_MAP_STYLE_URL ?? 'https://tiles.openfreemap.org/styles/dark', center: [8, 18], zoom: 1.45, minZoom: 1, maxZoom: 12, attributionControl: { compact: true } }); mapRef.current = map; map.addControl(new maplibregl.ScaleControl({ unit: 'metric' }), 'bottom-left');
    map.on('load', () => {
      map.addSource('weather-alerts', { type: 'geojson', data: alertPolygons(eventsRef.current) }); map.addSource('wildfires', { type: 'geojson', data: emptyCollection }); map.addSource('events', { type: 'geojson', data: eventPoints(eventsRef.current), cluster: true, clusterRadius: 42, clusterMaxZoom: 6 }); map.addSource('selected-event', { type: 'geojson', data: emptyCollection }); map.addSource('nearby-radius', { type: 'geojson', data: emptyCollection }); map.addSource('nearby-location', { type: 'geojson', data: emptyCollection });
      map.addLayer({ id: 'alert-fill', type: 'fill', source: 'weather-alerts', paint: { 'fill-color': '#ff8a4c', 'fill-opacity': 0.16 } }); map.addLayer({ id: 'alert-outline', type: 'line', source: 'weather-alerts', paint: { 'line-color': '#ffc06a', 'line-width': 1.5 } }); map.addLayer({ id: 'nearby-radius-fill', type: 'fill', source: 'nearby-radius', paint: { 'fill-color': '#55d3ca', 'fill-opacity': 0.06 } }); map.addLayer({ id: 'nearby-radius-line', type: 'line', source: 'nearby-radius', paint: { 'line-color': '#65ded5', 'line-width': 1.2, 'line-dasharray': [2, 2] } });
      map.addLayer({ id: 'fire-clusters', type: 'circle', source: 'wildfires', paint: { 'circle-color': '#f97316', 'circle-opacity': 0.7, 'circle-radius': ['interpolate', ['linear'], ['get', 'count'], 1, 3, 50, 13, 500, 22] } }); map.addLayer({ id: 'event-clusters', type: 'circle', source: 'events', filter: ['has', 'point_count'], paint: { 'circle-color': '#102b32', 'circle-stroke-color': '#55d3ca', 'circle-stroke-width': 1, 'circle-radius': ['step', ['get', 'point_count'], 13, 20, 17, 60, 21] } }); map.addLayer({ id: 'event-points', type: 'circle', source: 'events', filter: ['!', ['has', 'point_count']], paint: { 'circle-radius': 6, 'circle-color': ['match', ['get', 'type'], 'wildfire', '#fb923c', 'storm', '#a78bfa', 'volcano', '#fb923c', 'flood', '#60a5fa', 'earthquake', '#4dc5be', '#d4b46a'], 'circle-stroke-color': '#eefbff', 'circle-stroke-width': 0.8 } }); map.addLayer({ id: 'nearby-location-dot', type: 'circle', source: 'nearby-location', paint: { 'circle-radius': 6, 'circle-color': '#eaffff', 'circle-stroke-color': '#50d5ce', 'circle-stroke-width': 3 } }); map.addLayer({ id: 'selected-halo', type: 'circle', source: 'selected-event', paint: { 'circle-radius': 18, 'circle-color': '#67e8df', 'circle-opacity': 0.15, 'circle-stroke-color': '#87fff6', 'circle-stroke-width': 1.5 } });
      const select = (event: MapLayerMouseEvent) => { const id = event.features?.[0]?.properties?.id as string | undefined; const match = eventsRef.current.find((item) => item.id === id); if (match) onSelectRef.current(match); }; const selectFire = (event: MapLayerMouseEvent) => { const id = event.features?.[0]?.properties?.id as string | undefined; const match = observationsRef.current.find((item) => item.id === id); if (match) onSelectFireRef.current(match); }; map.on('click', 'event-points', select); map.on('click', 'alert-fill', select); map.on('click', 'fire-clusters', selectFire); ['event-points', 'alert-fill', 'fire-clusters'].forEach((layer) => { map.on('mouseenter', layer, () => { map.getCanvas().style.cursor = 'pointer'; }); map.on('mouseleave', layer, () => { map.getCanvas().style.cursor = ''; }); }); let viewportTimer: number | undefined; const publishViewport = () => { window.clearTimeout(viewportTimer); viewportTimer = window.setTimeout(() => { const bounds = map.getBounds(); onViewportChangeRef.current?.([bounds.getWest(), bounds.getSouth(), bounds.getEast(), bounds.getNorth()]); }, 300); }; map.on('moveend', publishViewport); publishViewport();
    });
    map.on('error', (event) => { if (!map.loaded() && event.error) setMapError(true); }); const observer = new ResizeObserver(() => map.resize()); observer.observe(containerRef.current); return () => { observer.disconnect(); map.remove(); mapRef.current = undefined; };
  }, []);
  useEffect(() => { const map = mapRef.current; if (!map?.isStyleLoaded()) return; (map.getSource('events') as GeoJSONSource | undefined)?.setData(eventPoints(events)); (map.getSource('weather-alerts') as GeoJSONSource | undefined)?.setData(alertPolygons(events)); }, [events]);
  useEffect(() => { const map = mapRef.current; if (!map?.isStyleLoaded()) return; (map.getSource('wildfires') as GeoJSONSource | undefined)?.setData(wildfireFeatures(observations)); }, [observations]);
  useEffect(() => { const map = mapRef.current; if (!map?.isStyleLoaded()) return; const data = selected?.latitude != null && selected.longitude != null ? eventPoints([selected]) : selectedFire ? wildfireFeatures([selectedFire]) : emptyCollection; (map.getSource('selected-event') as GeoJSONSource | undefined)?.setData(data); const point = selected ?? selectedFire; if (point?.latitude != null && point.longitude != null) map.easeTo({ center: [point.longitude, point.latitude], zoom: Math.max(map.getZoom(), 4), duration: 700 }); }, [selected, selectedFire]);
  useEffect(() => { const map = mapRef.current; if (!map?.isStyleLoaded() || !placeTarget) return; if (placeTarget.boundingBox) { const [west, south, east, north] = placeTarget.boundingBox; map.fitBounds([[west, south], [east, north]], { padding: 70, maxZoom: 9, duration: 700 }); } else map.easeTo({ center: [placeTarget.longitude, placeTarget.latitude], zoom: 7, duration: 700 }); }, [placeTarget]);
  useEffect(() => { const map = mapRef.current; if (!map?.isStyleLoaded()) return; const point = nearbyLocation ? { type: 'FeatureCollection' as const, features: [{ type: 'Feature' as const, properties: {}, geometry: { type: 'Point' as const, coordinates: [nearbyLocation.longitude, nearbyLocation.latitude] } }] } : emptyCollection; (map.getSource('nearby-location') as GeoJSONSource | undefined)?.setData(point); (map.getSource('nearby-radius') as GeoJSONSource | undefined)?.setData(nearbyLocation && radiusKm ? radiusPolygon(nearbyLocation.longitude, nearbyLocation.latitude, radiusKm) : emptyCollection); }, [nearbyLocation, radiusKm]);
  return <section className="map-panel" aria-label="Interactive global natural events map"><div ref={containerRef} className="map-canvas" /><div className="map-scanlines" aria-hidden="true" /><div className="map-label"><span>{nearbyLocation ? 'SELECTED LOCATION' : 'GLOBAL VIEW'}</span><strong>{nearbyLocation ? `${Math.round(radiusKm ?? 0)} KM RADIUS` : 'MULTI-SOURCE / LIVE'}</strong></div><div className="map-controls" aria-label="Map zoom controls"><Button variant="outline" size="icon-lg" aria-label="Zoom in" onClick={() => mapRef.current?.zoomIn()}><Plus /></Button><Button variant="outline" size="icon-lg" aria-label="Zoom out" onClick={() => mapRef.current?.zoomOut()}><Minus /></Button><Button variant="outline" size="icon-lg" aria-label="Reset global view" onClick={() => mapRef.current?.easeTo({ center: [8, 18], zoom: 1.45 })}><Crosshair /></Button></div><div className="map-legend"><span><i className="moderate" /> Events</span><span><i className="severe" /> Alerts</span><span><i className="high" /> Fire activity</span></div>{mapError && <div className="map-error">Basemap unavailable. Event feed remains active.</div>}</section>;
}

function radiusPolygon(longitude: number, latitude: number, radiusKm: number) { const coordinates: [number, number][] = []; const distance = radiusKm / 6371; const lat = latitude * Math.PI / 180; const lon = longitude * Math.PI / 180; for (let step = 0; step <= 64; step++) { const bearing = step / 64 * Math.PI * 2; const pointLat = Math.asin(Math.sin(lat) * Math.cos(distance) + Math.cos(lat) * Math.sin(distance) * Math.cos(bearing)); const pointLon = lon + Math.atan2(Math.sin(bearing) * Math.sin(distance) * Math.cos(lat), Math.cos(distance) - Math.sin(lat) * Math.sin(pointLat)); coordinates.push([((pointLon * 180 / Math.PI + 540) % 360) - 180, pointLat * 180 / Math.PI]); } return { type: 'FeatureCollection' as const, features: [{ type: 'Feature' as const, properties: {}, geometry: { type: 'Polygon' as const, coordinates: [coordinates] } }] }; }
