import { type EarthEvent, type EarthGeometry, type Severity } from '@earth-pulse/shared';
import { createHash } from 'node:crypto';
import { z } from 'zod';

const featureSchema = z.object({ id: z.string(), geometry: z.unknown().nullable(), properties: z.object({ event: z.string(), headline: z.string().nullable().optional(), description: z.string().nullable().optional(), severity: z.string().nullable().optional(), urgency: z.string().nullable().optional(), certainty: z.string().nullable().optional(), effective: z.string().nullable().optional(), onset: z.string().nullable().optional(), expires: z.string().nullable().optional(), sent: z.string().nullable().optional(), areaDesc: z.string().nullable().optional(), senderName: z.string().nullable().optional(), sender: z.string().nullable().optional(), '@id': z.string().url().nullable().optional() }) });
const responseSchema = z.object({ features: z.array(z.unknown()) });
const severityMap: Record<string, Severity> = { Minor: 'low', Moderate: 'moderate', Severe: 'severe', Extreme: 'extreme' };
function readGeometry(value: unknown): EarthGeometry | undefined { const parsed = z.union([z.object({ type: z.literal('Polygon'), coordinates: z.array(z.array(z.tuple([z.number(), z.number()]))).min(1) }), z.object({ type: z.literal('MultiPolygon'), coordinates: z.array(z.array(z.array(z.tuple([z.number(), z.number()])))).min(1) })]).safeParse(value); return parsed.success ? parsed.data : undefined; }
function centroid(value: EarthGeometry): [number, number] { const points = (value.type === 'Polygon' ? value.coordinates.flat() : value.coordinates.flat(2)) as [number, number][]; return points.reduce<[number, number]>((acc, p) => [acc[0] + (p[0] ?? 0) / points.length, acc[1] + (p[1] ?? 0) / points.length], [0, 0]); }
function iso(value: string | null | undefined) { const date = value ? new Date(value) : null; return date && !Number.isNaN(date.valueOf()) ? date.toISOString() : undefined; }
export function adaptNwsAlerts(input: unknown): { events: EarthEvent[]; rejectedCount: number } {
  const response = responseSchema.safeParse(input); if (!response.success) throw new Error('Invalid NWS response.'); const events: EarthEvent[] = []; let rejectedCount = 0;
  for (const raw of response.data.features) { const parsed = featureSchema.safeParse(raw); if (!parsed.success) { rejectedCount++; continue; } const item = parsed.data; const geometry = readGeometry(item.geometry); const point = geometry ? centroid(geometry) : null; const severity = severityMap[item.properties.severity ?? ''] ?? 'moderate'; const startedAt = iso(item.properties.onset) ?? iso(item.properties.effective) ?? iso(item.properties.sent) ?? new Date().toISOString(); const expiresAt = iso(item.properties.expires); const providerEventId = item.id; const publicId = createHash('sha256').update(providerEventId).digest('hex').slice(0, 24); events.push({ id: `nws:${publicId}`, type: 'weather-alert', subtype: item.properties.event.toLowerCase().replaceAll(' ', '-'), title: item.properties.headline ?? item.properties.event, ...(item.properties.description ? { description: item.properties.description } : {}), latitude: point?.[1] ?? null, longitude: point?.[0] ?? null, ...(geometry ? { geometry } : {}), startedAt, ...(expiresAt ? { endedAt: expiresAt } : {}), severity, severityScore: ({ low: 20, moderate: 40, high: 60, severe: 80, extreme: 100 } as const)[severity], source: 'NOAA National Weather Service', ...(item.properties['@id'] ? { sourceUrl: item.properties['@id'] } : {}), metadata: { kind: 'weather-alert', providerEventId, event: item.properties.event, ...(item.properties.headline ? { headline: item.properties.headline } : {}), ...(item.properties.areaDesc ? { areaDesc: item.properties.areaDesc } : {}), ...(item.properties.urgency ? { urgency: item.properties.urgency } : {}), ...(item.properties.certainty ? { certainty: item.properties.certainty } : {}), ...(iso(item.properties.effective) ? { effectiveAt: iso(item.properties.effective) } : {}), ...(expiresAt ? { expiresAt } : {}), ...(item.properties.senderName ? { senderName: item.properties.senderName } : {}), ...(item.properties.sender ? { issuingOffice: item.properties.sender } : {}) } }); }
  return { events, rejectedCount };
}
