import type { EarthObservation, ObservationFeature, ObservationsResponse } from '@earth-pulse/shared';
import { adaptFirmsObservations } from '../adapters/firmsObservationAdapter.js';
import { FirmsProvider } from '../providers/firms.js';
import { ProviderCache } from './providerCache.js';

interface ObservationSnapshot { observations: EarthObservation[]; rejectedCount: number }
export class ObservationService {
  private readonly cache: ProviderCache<ObservationSnapshot>;
  constructor(private readonly provider: Pick<FirmsProvider, 'fetchDetections' | 'configured'>, private readonly source: string, ttlMs = 900_000, cooldownMs = 30_000, maxStaleMs = 2 * 60 * 60_000) { this.cache = new ProviderCache(provider.configured, async () => adaptFirmsObservations(await provider.fetchDetections(), source), ttlMs, cooldownMs, maxStaleMs); }
  async getObservations(query: { bbox?: [number, number, number, number] | undefined; zoom?: number | undefined; force?: boolean | undefined } = {}): Promise<ObservationsResponse> { const snapshot = await this.cache.get(query.force); const observations = snapshot.value.observations; const zoom = query.zoom ?? 1; const inView = query.bbox ? observations.filter((observation) => within(observation, query.bbox!)) : observations; const raw = zoom >= 6 && inView.length <= 20_000; const features: ObservationFeature[] = raw ? inView.map((observation) => ({ ...observation, kind: 'observation' as const })) : aggregate(inView, zoom); return { features, totalDetections: observations.length, representation: raw ? 'observations' : 'clusters', meta: { fetchedAt: snapshot.fetchedAt, cache: snapshot.cache, provider: this.cache.status() } }; }
  async count(force = false) { try { return (await this.cache.get(force)).value.observations.length; } catch { return 0; } }
  status() { return this.cache.status(); }
}
function within(observation: EarthObservation, bbox: [number, number, number, number]) { const [west, south, east, north] = bbox; const longitudeOk = west <= east ? observation.longitude >= west && observation.longitude <= east : observation.longitude >= west || observation.longitude <= east; return longitudeOk && observation.latitude >= south && observation.latitude <= north; }
function aggregate(observations: EarthObservation[], zoom: number): ObservationFeature[] { const cell = zoom <= 2 ? 5 : zoom <= 4 ? 1 : 0.25; const bins = new Map<string, { latitude: number; longitude: number; count: number; latestAt: string; maxFireRadiativePower?: number }>(); for (const item of observations) { const longitude = Math.floor(item.longitude / cell) * cell + cell / 2; const latitude = Math.floor(item.latitude / cell) * cell + cell / 2; const id = `${longitude}:${latitude}`; const current = bins.get(id) ?? { longitude, latitude, count: 0, latestAt: item.observedAt }; current.count++; if (Date.parse(item.observedAt) > Date.parse(current.latestAt)) current.latestAt = item.observedAt; if (item.fireRadiativePower != null) current.maxFireRadiativePower = Math.max(current.maxFireRadiativePower ?? 0, item.fireRadiativePower); bins.set(id, current); } return [...bins.entries()].slice(0, 20_000).map(([id, value]) => ({ kind: 'cluster', id: `firms:grid:${cell}:${id}`, ...value })); }
